### ISSUE TITLE
<ol><li>

### ISSUE THREAD

**Issue by dyshero** [secanonm/delta_to_html#3]
<ol><li> 这个有问题，数字没有累加

**Comment by sidhu-patil** [comment]
thank you for reporting bug
i will fixed it on next update.

**Comment by navneet-singh-sengar** [comment]
Is any update?

**Comment by sidhu-patil** [comment]
problem fixed in delta_to_html >= 0.2.2

**Comment by navneet-singh-sengar** [comment]
I tested the updated code but still, some issues are there.

here is the input text
-----------------------------------
<img width="344" alt="Screenshot 2022-12-20 at 9 31 56 PM" src="https://user-images.githubusercontent.com/38186272/208711692-ce061a9f-067e-4f38-8558-7d77e82ed070.png">

and here is the output code
-----------------------------------
<img width="331" alt="Screenshot 2022-12-20 at 9 32 16 PM" src="https://user-images.githubusercontent.com/38186272/208711792-a1326446-77f6-4e3b-87d7-6ed3a4ad629a.png">

**Comment by sidhu-patil** [comment]
Please provide me your delta code

**Comment by navneet-singh-sengar** [comment]
insert⟨ Hello how are you⏎⏎Hello ⟩
insert⟨ ⏎ ⟩ + {list: ordered}
insert⟨ New ⟩
insert⟨ ⏎ ⟩ + {list: ordered}
insert⟨ Data ⟩
insert⟨ ⏎ ⟩ + {list: ordered}
insert⟨ Fine ⟩
insert⟨ ⏎ ⟩ + {list: ordered}
insert⟨ ⏎Yes wow⏎⏎Hello how⏎⏎Sdf ⟩
insert⟨ ⏎ ⟩ + {list: ordered}
insert⟨ Fs sdf sdf ⟩
insert⟨ ⏎ ⟩ + {list: ordered}
insert⟨ ⏎ ⟩
insert⟨ Sdfsdf sf ⟩ + {bold: true}
insert⟨ ⏎⏎Data A ⟩
insert⟨ ⏎ ⟩ + {list: ordered}
insert⟨ Data B ⟩
insert⟨ ⏎ ⟩ + {list: ordered}
insert⟨ Data C  ⟩
insert⟨ ⏎ ⟩ + {list: ordered}

**Comment by sidhu-patil** [comment]
In json format brother

**Comment by navneet-singh-sengar** [comment]
[{insert: Hello how are you
Hello }, {insert:, attributes: {list: ordered}}, {insert: New}, {insert:
, attributes: {list: ordered}}, {insert: Data}, {insert:
, attributes: {list: ordered}}, {insert: Fine}, {insert:
, attributes: {list: ordered}}, {insert:
Yes wow
Hello how
Sdf}, {insert:
, attributes: {list: ordered}}, {insert: Fs sdf sdf}, {insert:
, attributes: {list: ordered}}, {insert:
}, {insert: Sdfsdf sf, attributes: {bold: true}}, {insert:
Data A}, {insert:
, attributes: {list: ordered}}, {insert: Data B}, {insert:
, attributes: {list: ordered}}, {insert: Data C}, {insert:
, attributes: {list: ordered}}]
