### ISSUE TITLE
deltaToHTML no work for the properties of nested.

### ISSUE THREAD

**Issue by chifandeyu** [secanonm/delta_to_html#3]
> final delta = r '[{"insert":"1"},{"insert":"2","attributes":{"italic":true}},{"insert":"3","attributes":{"italic":true,"bold":true}},{"insert":"4","attributes":{"bold":true}}]'; final mk = deltaToHTML(delta); print('mk: $mk');
> 
> use this code

Sorry. I run this code with the latest version and still can't work.
![image](https://user-images.githubusercontent.com/15946864/171922946-f049e142-ee92-4c99-a716-36d083a47caf.png)

```
import 'package:delta_to_html/delta_to_html.dart';

void main() {
  final delta =
      r'[{"insert":"1"},{"insert":"2","attributes":{"italic":true}},{"insert":"3","attributes":{"italic":true,"bold":true}},{"insert":"4","attributes":{"bold":true}}]';
  final mk = deltaToHTML(delta);
  print('mk: $mk');
}
```

_Originally posted by @chifandeyu in https://github.com/secanonm/delta_to_html/issues/2#issuecomment-1146231986_

**Comment by secanonm** [comment]
import 'package:delta_to_html/delta_to_html.dart';

void main() {
  const delta =
      r'[{"insert":"1"},{"insert":"2","attributes":{"italic":true}},{"insert":"3","attributes":{"italic":true,"bold":true}},{"insert":"4","attributes":{"bold":true}},{"insert":"\n"}]';
  final html = deltaToHTML(delta);  
  // ignore: avoid_print
  print("HTML : $html");
}


This Code Definitely I didn't the exact why but currently we need to use ```{"insert":"\n"}``` as a last item of our list 

like _const delta =
r'[{"insert":"1"},{"insert":"2","attributes":{"italic":true}},{"insert":"3","attributes":{"italic":true,"bold":true}},{"insert":"4","attributes":{"bold":true}},**{"insert":"\n"}**]';_
may this help you 

Thank You

**Comment by chifandeyu** [comment]
> 

Thank you. Imodified it.But I don't know if this result is normal.
`flutter: HTML : 1<em>2<b>3</em>4</b>`

**Comment by secanonm** [comment]
it's because you use italic for 2 & 3 and on other hand you use bold for 3 & 4

that's the reason the code be like 

i know it's not  fully in html format but it can be excute as you want output 
`1<em>2</em> <b><em>3</em></b> <b>4</b>` or  `1<em>2<b>3</em>4</b>` both have same output 

thank you
