### ISSUE TITLE
can we have html to json quill....

### ISSUE THREAD

**Issue by pramod51** [secanonm/delta_to_html#4]
I want to make converted html to json for editing purpose...please help..

**Comment by sidhu-patil** [comment]
Yeah!, you can do it.
ok we can work together on it.

**Comment by pramod51** [comment]
i am working on it but not able write the correct code..

**Comment by nk4n01** [comment]
Hi, @pramod51 do you resolve this problem yet? I got the same.

**Comment by pramod51** [comment]
I have written my self for that

**Comment by sidhu-patil** [comment]
Sorry but I'm not focus on it, 
If you have code so you can pull a request and I will add your code in this repo 

Thank you

**Comment by chifandeyu** [comment]
Has anyone found any information about the conversion from html to quill delta？

**Comment by sidhu-patil** [comment]
Sorry, I'm not working on it ...
Thank you
