### ISSUE TITLE
Paragraphs instead BR?

### ISSUE THREAD

**Issue by mirozahorak** [secanonm/delta_to_html#7]
Hi, thanks for great converter!
Do you know how to force <p> instead <br> elements?

**Comment by sidhu-patil** [comment]
sorry, I didn't understand you,
can you please clarify the statement...
 
In HTML,
The paragraph is a block element which means the paragraph tag always ends with a newline and br is used for a newline .

we use be because user press enter which means newline not new para 

thank you
